language: ruby
cache: bundler
# Explicit usage of containerized builds, should provide faster feedback
# see https://docs.travis-ci.com/user/workers/container-based-infrastructure/
# and https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
before_install:
  - gem install bundler -v 1.13.7
before_script:
  - mysql -e 'create database acts_as_list;'
  - psql -c 'create database acts_as_list;' -U postgres
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-19mode
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
gemfile:
  - gemfiles/rails_3_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3_2.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails_5_1.gemfile
